plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace = "com.disastersos.app"
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        applicationId = "com.disastersos.app"
        minSdk = 27
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    buildFeatures {
        compose = true
    }
}

dependencies {
    // ── Generated by Android Studio — do not rename these ─────────────────
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3)
    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    debugImplementation(libs.androidx.compose.ui.tooling)
    debugImplementation(libs.androidx.compose.ui.test.manifest)

    // ── Disaster SOS POC ──────────────────────────────────────────────────

    // Extended icons — Warning, Wifi, WifiOff, LocationOn used in UI
    implementation("androidx.compose.material:material-icons-extended")

    // ViewModel + lifecycle for Compose (collectAsStateWithLifecycle)
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.0")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.8.0")

    // Nearby Connections — offline P2P mesh (THE core of this POC)
    implementation("com.google.android.gms:play-services-nearby:19.1.0")

    // Fused Location Provider — GPS coordinates for SOS message
    implementation("com.google.android.gms:play-services-location:21.3.0")

    // Coroutines — StateFlow, suspend functions, .await() on Play Services Tasks
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.8.1")

    // Accompanist Permissions — clean runtime permission handling in Compose
    implementation("com.google.accompanist:accompanist-permissions:0.34.0")

    // ── Phase 2: Offline Maps ─────────────────────────────────────────────
    // osmdroid — renders OpenStreetMap tiles 100% offline, no API key needed
    // Best Pakistan/Sindh coverage of any free offline map library
    implementation("org.osmdroid:osmdroid-android:6.1.18")
}